services:
  db:
    image: postgres:14.3
    container_name: keijupeli-postgres
    restart: always
    environment:
      POSTGRES_USER: keijupeli
      POSTGRES_PASSWORD: keijupeli
      POSTGRES_DB: keijupeli
    ports:
      - "3432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keijupeli"]
      interval: 10s
      timeout: 5s
      retries: 5
