name: Test Keijupeli

on: [workflow_dispatch, push]

jobs:
  build:
    name: Lint, typecheck, test and build
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: 'yarn'

      - name: Install deps
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn typecheck

      - name: Test
        run: yarn test

      - name: Build client
        run: yarn build-client

      - name: Build server
        run: yarn build-server
